version: "3"

services:
  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - database

networks:
  database:
    external:
      name: ${DATABASE_NETWORK}
